[package]
name = "astigeom"
version = "0.1.0"
authors = [" <arun.sivaramakrishnan@gmail.com>"]

[dependencies]
itertools = { git = "https://github.com/bluss/rust-itertools" }
la= "0.2.0"
nalgebra="0.10.*"
either="1.0.2"